import type { Hex } from './hex';
import type { RngState } from './rng';
import type { EventId, Resource, Season, Slot, TileType } from './content/schema';

export interface Tile extends Hex {
  type: TileType;
  /** Salvage left in a ruin. */
  salvage?: number;
  /** Position along the river, 0 at the upstream edge (river and reservoir tiles). */
  riverIndex?: number;
}

export interface MapState {
  width: number;
  height: number;
  /** Keyed by hexKey, in row-major order. */
  tiles: Record<string, Tile>;
  /** River tile keys from upstream to downstream. */
  river: string[];
  /** Floodplain tile keys, lowest ground first; a weir floods only the first part. */
  floodOrder: string[];
}

export type Stores = Record<Resource, number>;

export interface BuildingState {
  uid: string;
  type: string;
  at: Hex;
  /** Turn (0-based season count) the building was placed. */
  builtTurn: number;
  /** Year whose flood left silt on this farm. */
  siltYear?: number;
  /** Share of the silt boost it got (a levee with Silt Traps lets half through). */
  siltShare?: number;
  /** The building type it evolved from, and when (Milestone 6). */
  evolvedFrom?: string;
  evolvedTurn?: number;
  /** Disabled by an event. Flood damage needs a repair; storm damage clears next season. */
  damage?: { cause: 'flood' | 'storm'; turn: number };
  /** Selected recipe for workshops and kilns. */
  recipe?: string;
  /** Energy slot a digester feeds. */
  slot?: Slot;
  /** Stored energy or heat. */
  stored?: number;
}

export interface RunOptions {
  seed: string;
  /** The guided first year: fixed draft offers in year 1. */
  guided?: boolean;
  /** For testing and designers: every blueprint unlocked and 999 materials. */
  sandbox?: boolean;
  /** Offer a choice of visions (run goals) at the start. The design teaches them from run 4. */
  visions?: boolean;
  /** Tunings in the draft (from run 2) and charters at new eras (from run 3); both default on. */
  tunings?: boolean;
  charters?: boolean;
  /** What Root City gives this run: its districts' perks and cards, and its landmarks. */
  city?: RunCity;
  /** The expedition chosen for this run: its twist and its city request. */
  expedition?: RunExpedition;
}

export interface RunCity {
  /** The best tier of each district type in the city, by district id. */
  districts: Record<string, string>;
  landmarks: string[];
}

export interface RunExpedition {
  twist: string | null;
  request: string | null;
}

export interface DraftState {
  offer: string[];
  picked: string | null;
  /** A fourth card was bought this season. */
  extraBought: boolean;
}

export type RunStatus = 'active' | 'complete' | 'collapsed';

/** Totals over the whole run, for the score and the Graft offer. */
export interface Ledger {
  /** Energy generated by source type. */
  energy: Record<string, number>;
  foodMade: number;
  foodEaten: number;
  /** Sum over seasons of the citizens at the end of each. */
  citizenSeasons: number;
  /** Materials made by workshops and kilns. */
  industry: number;
}

export interface RunState {
  version: 2;
  contentId: string;
  options: Required<RunOptions>;
  rng: RngState;
  /** Seasons completed so far (0 to 48). */
  turn: number;
  year: number;
  season: Season;
  era: number;
  status: RunStatus;
  map: MapState;
  buildings: Record<string, BuildingState>;
  nextUid: number;
  /** Building types the player can place. */
  unlocked: string[];
  stores: Stores;
  citizens: number;
  wellbeing: number;
  harmony: number;
  draft: DraftState;
  /** This season's event (announced last season) and the next one. */
  forecast: { event: EventId; next: EventId };
  /** Building uids, highest priority first: staffed first, shut off last. */
  priority: string[];
  /** Energy supplied by source type in recent seasons (for the Mixed Grid bonus). */
  energyHistory: Record<string, number>[];
  /** Combos discovered this run, in order. */
  discoveries: string[];
  /** Closed loops: each keeps its bonus while it stands. */
  loops: LoopState[];
  /** Tunings drafted, and charters chosen, in order. */
  tunings: string[];
  charters: string[];
  /** Charters on offer at the start of an era; one must be chosen before the season ends. */
  charterOffer: string[];
  /** Almanac hints bought with knowledge this run. */
  hints: string[];
  /** Visions on offer at the start (one must be chosen), the chosen one, and when it was achieved. */
  visionOffer: string[];
  vision: string | null;
  visionAchieved: number | null;
  /** Eras whose goal has been met. */
  eraGoalsMet: number[];
  /** The turn the expedition's city request was met, or null. */
  requestMet: number | null;
  /** What this season's commands spent so far (building, rerolls, hints), for the season report. */
  spent: Flows;
  /** The reports of the last 4 seasons, oldest first: the last one of each season. */
  recentReports: SeasonReport[];
  ledger: Ledger;
  /** Messages for the player about things that happened between seasons. */
  notices: string[];
  lastReport: SeasonReport | null;
  history: SeasonSummary[];
  /** Undo support: the state at the start of the season and the commands since. */
  seasonStart: SeasonSnapshot | null;
  seasonCommands: Command[];
}

export interface LoopState {
  combo: string;
  /** The loop's first building (its composter, digester or fish pond). */
  anchor: string;
  /** Every building in the loop, anchor first. */
  members: string[];
  /** The turn it closed; its bonus starts the season after. */
  turn: number;
}

/** A combo at work this season: its buildings (or, for a strip, tile keys). */
export interface ComboHit {
  combo: string;
  members: string[];
  tiles?: string[];
}

export type SeasonSnapshot = Omit<RunState, 'seasonStart' | 'seasonCommands'>;

export type Command =
  | { type: 'pickCard'; card: string }
  | { type: 'pickCharter'; charter: string }
  | { type: 'pickVision'; vision: string }
  | { type: 'buyHint'; combo: string }
  | { type: 'rerollDraft' }
  | { type: 'buyExtraCard' }
  | { type: 'place'; building: string; at: Hex }
  | { type: 'spreadCompost'; at: Hex }
  /** Removes a building: energy this season, rubble, and the tile reverts (see rules.demolition). */
  | { type: 'demolish'; uid: string }
  | { type: 'setRecipe'; uid: string; recipe: string }
  | { type: 'setDigesterSlot'; uid: string; slot: Slot }
  | { type: 'setPriority'; order: string[] }
  | { type: 'undo' }
  | { type: 'endSeason' };

export type CommandResult = { ok: true; state: RunState } | { ok: false; error: string };

export interface HeatReport {
  /** Heat demanded by active buildings in this slot. */
  demand: number;
  /** Free heat generated (Solar Thermal Collectors), by source building type. */
  bySource: Record<string, number>;
  /** Free heat that paid heat demand directly. */
  free: number;
  /** Heat paid by heat pumps, and the energy they drew to do it. */
  pumped: number;
  pumpEnergy: number;
  /** Heat left to pay directly with energy, 1 for 1. */
  direct: number;
  /** Free heat put into Heat Wells. */
  stored: number;
}

export interface SlotReport {
  /** Energy generated, by source building type. */
  bySource: Record<string, number>;
  supply: number;
  /** Energy and heat demanded, by building type, before free heat and heat pumps. */
  demandBy: Record<string, number>;
  /**
   * Energy the slot's buildings need: their energy demand, plus heat paid
   * directly, plus the energy drawn by heat pumps.
   */
  demand: number;
  heat: HeatReport;
  /** Day energy set aside to charge storage that will cover a known shortfall. */
  reserved: number;
  /** Energy used by flexible consumers (workshop and kiln runs). */
  sponges: number;
  /** Energy put into storage from what was still spare (after sponges). */
  storageCharged: number;
  /** Energy or heat released from storage into this slot's shortfall. */
  storageDischarged: number;
  /** Demand still unmet after storage; blackouts close this gap. */
  shortfall: number;
  /** Spare energy nothing used. */
  unused: number;
}

export interface RunReport {
  /** The building's setting: a recipe id, or `auto`. */
  recipe: string;
  runs: number;
  energy: Record<Slot, number>;
  /** Runs of each recipe (Auto can mix them). */
  byRecipe: Record<string, number>;
}

export type WellbeingKind =
  'needsMet' | 'hunger' | 'unpowered' | 'clutter' | 'greenery' | 'civic' | 'formation' | 'charter';

export interface WellbeingLine {
  kind: WellbeingKind;
  reason: string;
  amount: number;
}

/** Where a resource came from or went, by what (a building's name, "citizens eat"...). */
export type FlowLines = Record<string, { amount: number; count: number }>;

/** Every unit of a resource made and used in a season: start + made − used = end. */
export type Flows = Partial<Record<Resource, { made: FlowLines; used: FlowLines }>>;

export interface SeasonReport {
  /**
   * Each resource made and used this season, by what: building, spending
   * during the season, eating, rot, bonuses, repairs. It balances exactly.
   */
  flows: Flows;
  turn: number;
  year: number;
  season: Season;
  event: EventId;
  mixedGrid: boolean;
  flooded: string[];
  silted: string[];
  damaged: string[];
  repaired: string[];
  unstaffed: string[];
  energy: Record<Slot, SlotReport>;
  runs: Record<string, RunReport>;
  /** Final yields per building uid. */
  yields: Record<string, Partial<Record<Resource, number>>>;
  /** Human-readable math per building uid, for tooltips. */
  math: Record<string, string[]>;
  bonuses: { apiary: number; compost: number };
  forage: number;
  improvedTiles: string[];
  blackouts: string[];
  food: { produced: number; eaten: number; unfed: number; rotted: number; storage: number };
  population: { before: number; change: number; after: number; reason: PopulationReason };
  wellbeing: { before: number; after: number; lines: WellbeingLine[] };
  clutter: { fromScraps: number; recycled: number; total: number };
  scraps: { fromCitizens: number; fromRot: number; total: number };
  harmony: { value: number; multiplier: number };
  /** Energy and free heat generated per building uid, by slot. */
  generated: Record<string, { energy: Record<Slot, number>; heat: Record<Slot, number> }>;
  /** Shaded solar per building uid: the keys of the tiles casting the shade. */
  shaded: Record<string, string[]>;
  /** Combos at work this season (step 10), and the ones discovered for the first time this run. */
  combos: ComboHit[];
  discoveries: string[];
  /** In a forecast: buildings the storm could disable (one of them will be, by chance). */
  atRisk: string[];
  /** Buildings that evolved at the end of this season. */
  evolved: { uid: string; from: string; into: string }[];
  /** The run's vision was achieved this season. */
  visionAchieved: boolean;
  /** The expedition's city request was met this season. */
  requestMet: boolean;
  /** The era whose goal was met this season, if any. */
  eraGoalMet: number | null;
}

/** Why the population did or didn't change this season. */
export type PopulationReason =
  'grew' | 'boom' | 'noHousing' | 'lowSpareFood' | 'lowWellbeing' | 'leaving';

export interface SeasonSummary {
  turn: number;
  year: number;
  season: Season;
  materials: number;
  food: number;
  citizens: number;
  wellbeing: number;
  harmony: number;
  shortfall: number;
  blackouts: number;
  /** Energy per slot, for the year strip. */
  energy: Record<Slot, { supply: number; demand: number; shortfall: number }>;
}
